### ISSUE TITLE
Error in running large dataset

### ISSUE THREAD

**Issue by zhou-1314** [slowkow/harmonypy#32]
First of all, thank you very much for migrating the Harmony algorithm from R to Python. Today, I encountered the following error while integrating 318,720 cells from different datasets using harmonypy. 
![error_information.png](https://s2.loli.net/2023/12/28/N3QL5Mcm74pudkw.png)
Hope to receive your help. Thank you.

**Comment by zhou-1314** [comment]
It's solved. when I used **harmony_integrate** function of scanpy, it's worked.
```
sce.pp.harmony_integrate(adata, 'aligned_dataset',basis='X_uce')
```

**Comment by slowkow** [comment]
Thanks for sharing your experience.

If we search the web for `"precompiled NUM_THREADS exceeded"` we can find many results with suggestions for how to solve this issue.

For example, [this Stackoverflow post](https://stackoverflow.com/questions/75619847/python-sklearn-openblas-error-for-kmeans) suggests that we can set the `NUM_THREADS` option like this:

```python
os.environ['OPENBLAS_NUM_THREADS'] = '1'
```

and then the `sklearn.KMeans` function should run without error.

I do not know whether or not this will fix your issue, because I don't know your system environment (python version, package versions, etc.).

**Comment by mrland99** [comment]
For people running jupyter notebook, running this in the first cell **before** importing any libraries works. 

%env OPENBLAS_NUM_THREADS=8
%env OMP_NUM_THREADS=8
%env MKL_NUM_THREADS=8
%env NUMEXPR_NUM_THREADS=8
